language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - composer install
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - find -type d -name vendor -prune -o -type f -name '*.php' -print0 | xargs -0 -n 1 php -l
  - phpcs -p --standard=PSR2 --extensions=php src
  - phpunit tests